### PR TITLE
added helper to get session cookie

### PR DESCRIPTION
**Pull request by wheresrhys**
@aintgoin2goa

### CODE REVIEW

**Comment by aintgoin2goa** [comment]
:+1:  but why?

**Comment by wheresrhys** [comment]
need it to communicate with user prefs api and it seems useful to put in a helper so that anyone else who needs user info doesn't have to mess with the cookie

**Comment by aintgoin2goa** [comment]
fair enough - I'll add you to the npm thing so you can publish what's your username?

**Comment by wheresrhys** [comment]
wheresrhys

**Comment by wheresrhys** [comment]
but does this work server side?

**Pull request merged**
